---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/skaffold version
    register: skaffold_test_output
  - name: skaffold version
    debug:
      msg: '{{ skaffold_test_output.stdout }}'
